In [1]:
import cv2 as cv
import numpy as np
kernel = np.ones((5, 5), np.uint8)

img = cv.imread("lena.jpg")
imgResize =cv.resize(img,(300,300))
imgGray = cv.cvtColor(imgResize, cv.COLOR_BGR2GRAY)
imgBlur = cv.GaussianBlur(imgGray,(7,7),0)
imgCanny=cv.Canny(imgResize,150,200)
imgDilate = cv.dilate(imgCanny,kernel,iterations=1)
imgEroded = cv.erode(imgDilate,kernel,iterations=1)



cv.imshow("orginal image",imgResize)
cv.waitKey(0)

cv.imshow("blur image",imgBlur)
cv.waitKey(0)

cv.imshow("gray image", imgGray)
cv.waitKey(0)

cv.imshow("Canny image", imgCanny)
cv.waitKey(0)

cv.imshow("Dilate image", imgDilate)
cv.waitKey(0)

cv.imshow("Erode image", imgEroded)
cv.waitKey(0)

13

In [1]:
import cv2 as cv
import numpy as np
img = cv.imread("lena.jpg")
print(img.shape)

imgResize = cv.resize(img,(300,300))
imgCrop = imgResize[50:150,50:150]

cv.imshow("lena",img)
cv.waitKey(0)

cv.imshow("resize lena",imgResize)
cv.waitKey(0)

cv.imshow("crop lena",imgCrop)
cv.waitKey(0)

    

(165, 165, 3)


-1

In [6]:
import cv2 as cv
import numpy as np

img = np.ones((512,512,3),np.uint8)
print(img)

img[200:300,100:300]=255,0,0

cv.imshow("image",img)

cv.waitKey(0)

[[[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 ...

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]]


-1

In [1]:
import cv2 as cv
import numpy as np

img = cv.imread("lena.jpg")

cv.line(img,(0,0),(100,100),(0,0,255))
cv.rectangle(img,(0,0),(50,100),(255,0,0),3)
cv.circle(img,(50,80),40,(0,255,0),3)
cv.putText(img,"lena",(40,140),cv.FONT_HERSHEY_COMPLEX,1,(0,150,0),3)

cv.imshow("lineImage",img)
cv.waitKey(0)




13

In [1]:
import cv2 as cv
import numpy as np

def empty(a):
    pass

img = cv.imread("lena.jpg")

cv.namedWindow("TrackBars")
cv.resizeWindow("TrackBars",640,240)
cv.createTrackbar("hue min","TrackBars",0,179,empty)
cv.createTrackbar("hue max","TrackBars",23,179,empty)
cv.createTrackbar("sat min","TrackBars",27,255,empty)
cv.createTrackbar("sat max","TrackBars",255,255,empty)
cv.createTrackbar("val min","TrackBars",207,255,empty)
cv.createTrackbar("val max","TrackBars",255,255,empty)

while True:
    imgResize = cv.resize(img,(300,300))
    imgHSV = cv.cvtColor(imgResize,cv.COLOR_BGR2HSV)
    h_min = cv.getTrackbarPos("hue min","TrackBars")
    h_max = cv.getTrackbarPos("hue max","TrackBars")
    s_min = cv.getTrackbarPos("sat min","TrackBars")
    s_max = cv.getTrackbarPos("sat max","TrackBars")
    v_min = cv.getTrackbarPos("val min","TrackBars")
    v_max = cv.getTrackbarPos("val max","TrackBars")
    
    lower = np.array([h_min,s_min,v_min])
    upper = np.array([h_max,s_max,v_max])
    
    mask = cv.inRange(imgHSV,lower,upper)
    #imgResult = cv.bitwise_and(img,img,mask=mask)
    

    #cv.imshow("orginal image",imgResize)
    #cv.waitKey(0)
    cv.imshow("orginal image",img)
    cv.imshow("HSV image",imgHSV)
    cv.imshow("mask",mask)
    #cv.imshow("img result",imgResult)
    cv.waitKey(1)


error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window_w32.cpp:2581: error: (-27:Null pointer) NULL window: 'TrackBars' in function 'cvGetTrackbarPos'


NameError: name 'cv' is not defined

In [3]:

print("a")

a


In [ ]:
import cv2 as cv
import numpy as np

img = cv.imread("shapes.jpg")
#imgGray = cv.cvtColor(img,cv.COLOR_BGR2GRAY)
#imgBlur = cv.GaussianBlur(imgGray,(7,7),1)
def getContours(img):
    contours,hierarchy = cv.findContours(img,cv.RETR_EXTERNAL,cv.CHAIN_APPROX_NONE)
    for cnt in contours:
        area = cv.contourArea(cnt)
        print(area)
        cv.drawContours(img,cnt,-1,(255,0,0),3)

cv.imshow("orginal image",img)
cv.waitKey(0)
getContours(img)
#cv.imshow("Gray image",imgGray)
#cv.waitKey(0)
#cv.imshow("Blur image",imgBlur)
#cv.waitKey(0)


In [3]:
import cv2 as cv
import numpy as np

faceCascade = cv.CascadeClassifier("haarcascade frontalface_default.xml")
img = cv.imread("lena.jpg")

imgGray = cv.cvtColor(img,cv.COLOR_BGR2GRAY)

faces = faceCascade.detectMultiScale(imgGray,1,4)

for(x,y,w,h) in faces:
    cv.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
    
cv.imshow("result",img)
cvc.waitKey(0)
    

error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\objdetect\src\cascadedetect.cpp:1689: error: (-215:Assertion failed) !empty() in function 'cv::CascadeClassifier::detectMultiScale'
